# Generated by Django 4.0.5 on 2022-08-02 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=255)),
                ('fullname', models.CharField(max_length=255)),
                ('gender', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
                ('subject', models.CharField(max_length=500)),
                ('education', models.TextField()),
                ('picture', models.ImageField(upload_to='tutors/images/')),
                ('contact', models.CharField(max_length=500)),
            ],
        ),
    ]
